name: build-qxdl
on:
  workflow_dispatch: {}       # 手动触发
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
          cache: true
      - name: Tidy (ok if no deps)
        run: go mod tidy
      - name: Build Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o qxdl.exe .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qxdl-windows-amd64
          path: qxdl.exe
